### ISSUE TITLE
Please Help! Where is v4.0? I can not upload .lns by Snap Camera Service v3.2

### ISSUE THREAD

**Issue by xys123** [ptrumpis/snap-lens-cache-import#3]
In the tool (https://ptrumpis.github.io/snap-lens-cache-import/#) notice : 
API Error: no response

Docker log:
2024-09-22 22:37:29 webproxy-1  | 2024/09/22 14:37:29 [warn] 40#40: *20 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000002, client: 172.18.0.1, server: studio-app.snapchat.com, request: "POST /vc/v1/import/lens HTTP/1.1", host: "studio-app.snapchat.com", referrer: "https://ptrumpis.github.io/"
2024-09-22 22:37:29 webapp-1    | Undocumented POST URL: /vc/v1/import/lens {}
2024-09-22 22:37:29 webproxy-1  | 172.18.0.1 - - [22/Sep/2024:14:37:29 +0000] "POST /vc/v1/import/lens HTTP/1.1" 200 2 "https://ptrumpis.github.io/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0" "-"

**Comment by xys123** [comment]
By the way.I have tried to use Snap Camera Patch.And searched also failed.
Docker log:

> 2024-09-22 22:52:14 webapp-1    | FetchError: request to https://lens.snapchat.com/bf3798795ebb46e0ac6c2c3d5206f462 failed, reason: Client network socket disconnected before secure TLS connection was established
> 2024-09-22 22:52:14 webapp-1    |     at ClientRequest.<anonymous> (file:///usr/src/app/node_modules/node-fetch/src/index.js:108:11)
> 2024-09-22 22:52:14 webapp-1    |     at ClientRequest.emit (node:events:513:28)
> 2024-09-22 22:52:14 webapp-1    |     at TLSSocket.socketErrorListener (node:_http_client:494:9)
> 2024-09-22 22:52:14 webapp-1    |     at TLSSocket.emit (node:events:513:28)
> 2024-09-22 22:52:14 webapp-1    |     at emitErrorNT (node:internal/streams/destroy:157:8)
> 2024-09-22 22:52:14 webapp-1    |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
> 2024-09-22 22:52:14 webapp-1    |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
> 2024-09-22 22:52:14 webapp-1    |   type: 'system',
> 2024-09-22 22:52:14 webapp-1    |   errno: 'ECONNRESET',
> 2024-09-22 22:52:14 webapp-1    |   code: 'ECONNRESET',
> 2024-09-22 22:52:14 webapp-1    |   erroredSysCall: undefined
> 2024-09-22 22:52:14 webapp-1    | }
> 2024-09-22 22:52:14 webapp-1    | Error: cheerio.load() expects a string
> 2024-09-22 22:52:14 webapp-1    |     at Module.load (file:///usr/src/app/node_modules/cheerio/dist/esm/load.js:22:19)
> 2024-09-22 22:52:14 webapp-1    |     at SnapLensWebCrawler.getLensByHash (file:///usr/src/app/src/lib/crawler.js:19:31)
> 2024-09-22 22:52:14 webapp-1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 2024-09-22 22:52:14 webapp-1    |     at async Module.search (file:///usr/src/app/src/utils/web.js:19:22)
> 2024-09-22 22:52:14 webapp-1    |     at async file:///usr/src/app/src/endpoints/search.js:45:26
> 2024-09-22 22:52:14 webproxy-1  | 172.18.0.1 - - [22/Sep/2024:14:52:14 +0000] "POST /vc/v1/explorer/search HTTP/1.1" 200 13 "-" "SnapCamera/1.21.0.0 (Windows 11 Version 2009)" "-"

**Comment by xys123** [comment]
> By the way.I have tried to use Snap Camera Patch.And searched also failed. Docker log:
> 
> > 2024-09-22 22:52:14 webapp-1    | FetchError: request to https://lens.snapchat.com/bf3798795ebb46e0ac6c2c3d5206f462 failed, reason: Client network socket disconnected before secure TLS connection was established
> > 2024-09-22 22:52:14 webapp-1    |     at ClientRequest. (file:///usr/src/app/node_modules/node-fetch/src/index.js:108:11)
> > 2024-09-22 22:52:14 webapp-1    |     at ClientRequest.emit (node:events:513:28)
> > 2024-09-22 22:52:14 webapp-1    |     at TLSSocket.socketErrorListener (node:_http_client:494:9)
> > 2024-09-22 22:52:14 webapp-1    |     at TLSSocket.emit (node:events:513:28)
> > 2024-09-22 22:52:14 webapp-1    |     at emitErrorNT (node:internal/streams/destroy:157:8)
> > 2024-09-22 22:52:14 webapp-1    |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
> > 2024-09-22 22:52:14 webapp-1    |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
> > 2024-09-22 22:52:14 webapp-1    |   type: 'system',
> > 2024-09-22 22:52:14 webapp-1    |   errno: 'ECONNRESET',
> > 2024-09-22 22:52:14 webapp-1    |   code: 'ECONNRESET',
> > 2024-09-22 22:52:14 webapp-1    |   erroredSysCall: undefined
> > 2024-09-22 22:52:14 webapp-1    | }
> > 2024-09-22 22:52:14 webapp-1    | Error: cheerio.load() expects a string
> > 2024-09-22 22:52:14 webapp-1    |     at Module.load (file:///usr/src/app/node_modules/cheerio/dist/esm/load.js:22:19)
> > 2024-09-22 22:52:14 webapp-1    |     at SnapLensWebCrawler.getLensByHash (file:///usr/src/app/src/lib/crawler.js:19:31)
> > 2024-09-22 22:52:14 webapp-1    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > 2024-09-22 22:52:14 webapp-1    |     at async Module.search (file:///usr/src/app/src/utils/web.js:19:22)
> > 2024-09-22 22:52:14 webapp-1    |     at async file:///usr/src/app/src/endpoints/search.js:45:26
> > 2024-09-22 22:52:14 webproxy-1  | 172.18.0.1 - - [22/Sep/2024:14:52:14 +0000] "POST /vc/v1/explorer/search HTTP/1.1" 200 13 "-" "SnapCamera/1.21.0.0 (Windows 11 Version 2009)" "-"

Ignore this problem. It works today.  May need restart computer.
